Add arg for constant pad value in read.from_np
gdsfactory/gdsfactory pull request #2582
Opened 2024-03-04 21:56 UTC by thomasdorch

Added an optional argument to `read.from_np` to allow user to specify a value to pad the image array with.

2024-03-04 22:19 UTC, joamatab requested changes
Thank you Thomas!

2024-03-04 22:19 UTC, joamatab commented on gdsfactory/read/from_np.py
> +        outer_pad_value: set outer padding used by np.pad to this constant value (optional).
is this in um or pixels?

how about calling it padding? we already have the concept of padding, which is in um,

some ideas are

- padding (if it's um)
- padding_pixels (if it's in pixels)

2024-03-05 19:45 UTC, thomasdorch commented
@joamatab I made the description more specific to indicate that the value is used to set the border pixel values but let me know if something else needs to change for this to get merged

2024-03-06 05:26 UTC, joamatab commented
I think the variable name could be a bit better

How about `outer_pad_pixels`?

2024-03-06 20:57 UTC, thomasdorch commented
@joamatab Thanks for the feedback! I added an arg for the number of pixels to pad with as well and changed the names to hopefully more clear. Let me know if this is good

Also, not sure what happened with my rebase initially I fixed it now and it should be just the 3 commits.

2024-03-06 21:13 UTC, joamatab commented
awesome! thank you Thomas!

2024-03-06 21:14 UTC, joamatab approved these changes

2024-03-06 21:14 UTC, merged